ALTER TABLE news ADD COLUMN IF NOT EXISTS url VARCHAR(2048);
ALTER TABLE news ADD COLUMN IF NOT EXISTS "imageUrl" VARCHAR(1000);
ALTER TABLE news ADD COLUMN IF NOT EXISTS "imageAlt" VARCHAR(500);
ALTER TABLE news ADD COLUMN IF NOT EXISTS tags VARCHAR(500);
ALTER TABLE news ADD COLUMN IF NOT EXISTS summary TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_news_url ON news(url) WHERE url IS NOT NULL;
