ALTER TABLE news ADD COLUMN url TEXT;
ALTER TABLE news ADD COLUMN imageUrl TEXT;
ALTER TABLE news ADD COLUMN imageAlt TEXT;
ALTER TABLE news ADD COLUMN tags TEXT;
ALTER TABLE news ADD COLUMN summary TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_news_url ON news(url);
