-- Add domain/AI tech imperative sections and share tracking to news
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='news' AND COLUMN_NAME='domainImperative')
  ALTER TABLE news ADD domainImperative NVARCHAR(MAX);
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='news' AND COLUMN_NAME='aiTechImperative')
  ALTER TABLE news ADD aiTechImperative NVARCHAR(MAX);
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='news' AND COLUMN_NAME='shares')
  ALTER TABLE news ADD shares INT NOT NULL DEFAULT 0;
