ALTER TABLE news ADD COLUMN IF NOT EXISTS "domainImperative" TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS "aiTechImperative" TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS shares INT NOT NULL DEFAULT 0;
