IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'keyMoments' AND COLUMN_NAME = 'domain')
BEGIN
  ALTER TABLE keyMoments ADD domain NVARCHAR(255) NOT NULL CONSTRAINT DF_keyMoments_domain DEFAULT '';
END
GO